server:
  port: 8888
spring:
  profiles:
    active: local
  jpa:
    open-in-view=false
  hibernate:
    format_sql: true
  properties:
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
