version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todoca-db
    environment:
      POSTGRES_DB: todoca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
